import { ReactNode } from "react";
export function AlertDialog({ open, onOpenChange, children }: { open: boolean; onOpenChange: (o:boolean)=>void; children: ReactNode; }) { if (!open) return null; return (<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={() => onOpenChange(false)} /><div className="relative z-10 w-full max-w-md">{children}</div></div>); }
export function AlertDialogContent({ children, className }: { children: ReactNode; className?: string }) { return <div className={`rounded-xl border border-slate-200 bg-white shadow-xl ${className||""}`}>{children}</div>; }
export function AlertDialogHeader({ children }: { children: ReactNode }) { return <div className="px-6 pt-6 pb-4">{children}</div>; }
export function AlertDialogTitle({ children, className }: { children: ReactNode; className?: string }) { return <h3 className={`text-lg font-semibold text-slate-900 ${className||""}`}>{children}</h3>; }
export function AlertDialogDescription({ children, className }: { children: ReactNode; className?: string }) { return <p className={`text-sm text-slate-500 mt-1 ${className||""}`}>{children}</p>; }
export function AlertDialogFooter({ children }: { children: ReactNode }) { return <div className="px-6 py-4 border-t border-slate-100 flex justify-end gap-2">{children}</div>; }
export function AlertDialogCancel({ children, onClick, className }: { children: ReactNode; onClick?: ()=>void; className?: string }) { return <button onClick={onClick} className={`px-4 py-2 rounded-lg border border-slate-200 text-sm text-slate-700 hover:bg-slate-50 ${className||""}`}> {children} </button>; }
export function AlertDialogAction({ children, onClick, className }: { children: ReactNode; onClick?: ()=>void; className?: string }) { return <button onClick={onClick} className={`px-4 py-2 rounded-lg text-sm font-medium ${className||"bg-slate-900 text-white hover:bg-slate-800"}`}> {children} </button>; }
